#pragma once

#include "plugin_settings.h"
#include "../io/display_manager.h"
#include <cstdint>

namespace OpenChord {

// Forward declarations
class IPluginWithSettings;

/**
 * Settings Manager - Handles plugin settings UI and editing
 * 
 * Responsibilities:
 * - Display list of settings for a plugin
 * - Handle encoder rotation for value changes (real-time)
 * - Handle encoder press for toggles/cycles
 * - Navigate settings list with joystick
 * - Render settings UI (auto-generated or custom)
 */
class SettingsManager {
public:
    SettingsManager();
    ~SettingsManager();
    
    // Initialization
    void Init(DisplayManager* display);
    
    // Set the plugin whose settings to display/edit
    void SetPlugin(IPluginWithSettings* plugin);
    
    // Get current plugin
    IPluginWithSettings* GetPlugin() const { return current_plugin_; }
    
    // Navigation
    void SetSelectedIndex(int index);
    int GetSelectedIndex() const { return selected_index_; }
    void MoveSelection(int direction);  // +1 for down, -1 for up
    
    // Value editing
    void ChangeValue(float delta);  // Rotate encoder
    void ToggleValue();             // Press encoder (for bool/enum)
    
    // Rendering
    void Render();
    
    // Health check
    bool IsHealthy() const { return display_ != nullptr && display_->IsHealthy(); }
    
private:
    DisplayManager* display_;
    IPluginWithSettings* current_plugin_;
    int selected_index_;
    
    // Cached setting info
    int setting_count_;
    
    void RenderAutoGeneratedUI();
    void RenderSettingItem(int index, bool is_selected, int y_pos);
    void UpdateValue(int setting_index, float delta);
    void CycleEnumValue(int setting_index);
};

} // namespace OpenChord
